### ISSUE TITLE
plsss update YTSytemAppearance

### ISSUE THREAD

**Issue by binnichtaktiv** [PoomSmart/YTSystemAppearance#1]
i know its not the right place but can you please update YTSytemAppearance so that it works with the latest yt version? :)

**Comment by PoomSmart** [comment]
@binnichtaktiv Your device OS version? Your YouTube version? How does it not work?

**Comment by binnichtaktiv** [comment]
> @binnichtaktiv Your device OS version? Your YouTube version? How does it not work?

iOS 13.3 latest yt version 17.05.2. YTSystemAppereance should change automatically to darkmode if iOS darkmode is enabled right? Or do I misunderstand something

**Comment by PoomSmart** [comment]
@binnichtaktiv YT app should toggle between light and dark mode automatically as you toggle system light or dark mode.

**Comment by binnichtaktiv** [comment]
> @binnichtaktiv YT app should toggle between light and dark mode automatically as you toggle system light or dark mode.

Yeah but it doesn’t do that automatically

**Comment by dayanch96** [comment]
> > @binnichtaktiv YT app should toggle between light and dark mode automatically as you toggle system light or dark mode.
> 
> Yeah but it doesn’t do that automatically

Did you selected 'Use device theme' in YT Settings?

**Comment by binnichtaktiv** [comment]
> > > @binnichtaktiv YT app should toggle between light and dark mode automatically as you toggle system light or dark mode.
> > 
> > 
> > Yeah but it doesn’t do that automatically
> 
> Did you selected 'Use device theme' in YT Settings?

Nevermind got it working after messing around with it. Idc what the problem was😅
